server {
    listen 80;
    server_name localhost;

    server_tokens off;

    # Security Headers
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://tveahlfmuxnseeoknioq.supabase.co https://*.supabase.co; connect-src 'self' http://localhost:3000 https://tveahlfmuxnseeoknioq.supabase.co https://*.googleapis.com;" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
